#!/bin/bash

N="traces"
cd $(dirname $0)

# Alacritty
! [ -d "$HOME/.config/alacritty/lib" ] && mkdir -p $HOME/.config/alacritty/lib
cp ./alacritty.toml $HOME/.config/alacritty/lib/$N.toml

# Polybar
! [ -d "$HOME/.config/polybar/" ] && mkdir $HOME/.config/polybar/
cp ./polybar.ini $HOME/.config/polybar/$N.ini

# Rofi
! [ -d "$HOME/.local/share/rofi/themes/" ] && mkdir -p $HOME/.local/share/rofi/themes/
cp ./theme.rasi $HOME/.local/share/rofi/themes/$N.rasi
! [ -d $HOME/.local/share/rofi/icons ] && mkdir $HOME/.local/share/rofi/icons/
cp ./fallback-icon.svg $HOME/.local/share/rofi/icons/$N.svg
