(load-theme 'doom-challenger-deep t)
(set-face-background 'default "#0E0C21")
(set-face-foreground 'default "#ffffff")
(set-frame-parameter (selected-frame) 'internal-border-width 1)
(set-face-background 'internal-border "#dfc2ff")
(set-face-background 'fringe (face-attribute 'default :background))
